apiVersion: v1
kind: Service
metadata:
  name: &app-name svc-go-ledger
  namespace: test-a
  labels:
    app: *app-name
spec:
  type: ClusterIP
  ports:
  - port: 6003
    targetPort: 6003
    protocol: TCP
    name: http
  selector:
    app: go-ledger
